### ISSUE TITLE
There are no core dumps for scylla bad_alloc in dtests

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#134]
Seen in [scylladb/scylla#4235](https://github.com/scylladb/scylla/issues/4235)

@tgrabiec suggests:

> We should run dtests with `--abort-on-seastar-bad-alloc` and `--abort-on-lsa-bad-alloc=1` so that we get a core dump to analyze.

**Comment by bhalevy** [comment]
This could be added by default to cluster.set_configuration_options with a parameter that could be used to override it if needed.

**Comment by tgrabiec** [comment]
Depends on https://github.com/scylladb/scylla/issues/2924, on which I am working now.

**Comment by bhalevy** [comment]
Closing as per scylladb/scylla-pkg#264
