### ISSUE TITLE
scylla processes show up as ld-linux-x86-64 instead of scylla

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#149]
Issue moved here from scylladb/scylla-dtest#954

Commit b84d6dcb7a86bd770880d55d3dc23429329dc87d causes the scylla processes to be wrongly named as `ld-linux-x86-64`.

This should be fixed in high priority as it confuses dtest cluster cleanup and other functions that look for processes called `scylla`

**Comment by fruch** [comment]
I think 
https://github.com/scylladb/scylla-ccm/pull/150
would fix the issue
