### ISSUE TITLE
Manager doesn't seem to start

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-ccm#187]
As seen on this run https://jenkins.scylladb.com/view/mermaid/job/mermaid-master-dtest-new/25/console (using the next branch) it seems that the manager itself fails to start whenever I try to run a manager related test

**Comment by ShlomiBalalis** [comment]
@fruch

**Comment by fruch** [comment]
Didn't we pinpointed this issue as a manager issue ? I.e. log of manager would help understand if it's that issue

**Comment by ShlomiBalalis** [comment]
It seems it was occurring due to a manager issue, closing
