### ISSUE TITLE
rewriting install.sh by sed causes syntax error

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-ccm#249]
We currently causing bash syntax error on install.sh while merging scylladb/scylla#7187, likely because we tries to add one more bash function to call systemctl:
```
/jenkins/workspace/scylla-master/next/scylla/.ccm/scylla-repository/5d75ecb069f7db44b0457a634edf9ed596d3de95/scylla-core-package/install.sh: line 386: syntax error near unexpected token `fi'
21:33:39  start_stop_test_node (bootstrap_test.TestBootstrap) ... ERROR
```
Also see: https://groups.google.com/g/scylladb-dev/c/9mK1qMnPEV4/m/w3DeyMB7AQAJ

It's better to use install.sh option to skip systemctl instead of rewriting by sed, it can easily break the script.
I going to merge a patch to support --packaging with nonroot mode, so we can use the option:
https://github.com/scylladb/scylla/pull/7405

**Comment by syuu1228** [comment]
BTW we also better to remove one more sed: https://github.com/scylladb/scylla-ccm/blob/next/ccmlib/scylla_repository.py#L238
I guess we can just drop it, and then run install.sh without specifying --root, add root prior to prefix like this:
`install.sh --prefix $root/$prefix --nonroot`

**Comment by fruch** [comment]
> BTW we also better to remove one more sed: https://github.com/scylladb/scylla-ccm/blob/next/ccmlib/scylla_repository.py#L238
> I guess we can just drop it, and then run install.sh without specifying --root, add root prior to prefix like this:
> `install.sh --prefix $root/$prefix --nonroot`

Last time we tried doing that it wasn't working as we expected, and we didn't had time to look into it further.
I you can fix both sides to play along with patches, that would be great.
