### ISSUE TITLE
The dtest manager test failing due to Scylla version mismatch (got Scylla 3.0 and not 4.1)

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla-ccm#252]
The `manager_health_check_test.test_health_check_metrics` dtest test failed because the cluster version `3.0` and not `4.1` (The CCM version function returns incorrect cluster version).

```
+----+----------+----------+------------+-----------+------+----------+--------------------------------+-----------------------------+--------------------------------------+
|    | CQL      | REST     | Address    | Uptime    | CPUs | Memory   | Scylla                         | Agent                       | Host ID                              |
+----+----------+----------+------------+-----------+------+----------+--------------------------------+-----------------------------+--------------------------------------+
| DN | -        | -        | 127.0.81.1 | -         | -    | -        | -                              | -                           | 4174891b-0ee1-4a98-97a8-6463a4a33eab |
| UN | UP (0ms) | UP (0ms) | 127.0.81.2 | 72h21m28s | 8    | 31.18GiB | 4.1.rc2-0.20200608.67348cd6e8e | 666.dev-0.20201014.fae52058 | 05e0e94e-9f9f-4cb6-93a9-5915a7e90c04 |
| UN | UP (0ms) | UP (0ms) | 127.0.81.3 | 72h21m28s | 8    | 31.18GiB | 4.1.rc2-0.20200608.67348cd6e8e | 666.dev-0.20201014.fae52058 | 553f4400-b619-4f31-ad20-77350c5e9d82 |
+----+----------+----------+------------+-----------+------+----------+--------------------------------+-----------------------------+--------------------------------------+
```

https://jenkins.scylladb.com/job/mermaid-master/job/mermaid-dtest/573/testReport/manager_health_check_tests/ManagerHealthCheckTest/test_health_check_metrics/

**Comment by Orenef11** [comment]
FYI
@fruch

**Comment by fruch** [comment]
@bhalevy  I think #248 isn't working for Oren, as we would expect.

**Comment by bhalevy** [comment]
Why does this detail matters for the test?

Anyhow, from https://jenkins.scylladb.com/job/mermaid-master/job/mermaid-dtest/573/artifact/scylla-dtest/logs/dtest.log, it looks like ccm started returning the actual `scylla_version` rather than the bogus `3.0` version.
```
2020-10-15 03:52:28,903 529     dtest                          DEBUG    | manager_backup_tests.py:TestScyllaMgmtBackup.test_backup_files_command_with_many_sstable_files - Initiating Scylla-Manager, version: ([['Client version: 666.dev-0.20201014.fae52058'], ['Server version: 666.dev-0.20201014.fae52058']], '')
```

The reason `cluster.version()` returns `3.0` is that the `666.dev-0.20201014.fae52058` version is malformed.
See https://github.com/scylladb/scylla-ccm/blob/40ff4e2cfa7dc90e8c511a81888b25dee3c15215/ccmlib/common.py#L616-L627

I'm currently testing a change in scylla that will change the version to `4.3.dev`  and I expect it to fix this issue as well.

See https://github.com/scylladb/scylla-dev/commit/a9c2ab92536896ee3256a6d4506a4d712c7cecea
https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/1058

**Comment by bhalevy** [comment]
@Orenef11 I suggest changing the title of this issue since ccm actually started returning the actual scylla version rather than the incorrect one it used to return before.  I'd stick to just describing what went wrong - i.e. test_health_check_metrics failing due to scylla_version mismatch.

**Comment by Orenef11** [comment]
> Why does this detail matters for the test?
> 
> Anyhow, from https://jenkins.scylladb.com/job/mermaid-master/job/mermaid-dtest/573/artifact/scylla-dtest/logs/dtest.log, it looks like ccm started returning the actual `scylla_version` rather than the bogus `3.0` version.
> 
> ```
> 2020-10-15 03:52:28,903 529     dtest                          DEBUG    | manager_backup_tests.py:TestScyllaMgmtBackup.test_backup_files_command_with_many_sstable_files - Initiating Scylla-Manager, version: ([['Client version: 666.dev-0.20201014.fae52058'], ['Server version: 666.dev-0.20201014.fae52058']], '')
> ```
> 
> The reason `cluster.version()` returns `3.0` is that the `666.dev-0.20201014.fae52058` version is malformed.
> See
> 
> https://github.com/scylladb/scylla-ccm/blob/40ff4e2cfa7dc90e8c511a81888b25dee3c15215/ccmlib/common.py#L616-L627
> 
> I'm currently testing a change in scylla that will change the version to `4.3.dev` and I expect it to fix this issue as well.
> 
> See [scylladb/scylla-dev@a9c2ab9](https://github.com/scylladb/scylla-dev/commit/a9c2ab92536896ee3256a6d4506a4d712c7cecea)
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/1058

@bhalevy 
I do not think the change will help, because now the test will fail. 
After all, the cluster version is 4.3, but the actual Scylla version is 4.1.
Apart from this test, other manager tests check the Scylla version to validate the manager returns the correct version.

**Comment by Orenef11** [comment]
> @Orenef11 I suggest changing the title of this issue since ccm actually started returning the actual scylla version rather than the incorrect one it used to return before. I'd stick to just describing what went wrong - i.e. test_health_check_metrics failing due to scylla_version mismatch.

@bhalevy 
I changed the bug title, but if it's still not good, you can change it

**Comment by bhalevy** [comment]
Where should 4.1 come from?
