### ISSUE TITLE
Starting scylla with --kernel-page-cache is not supported by older scylla versions

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#318]
PR #317 caused a regression in rolling_upgrade_test.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/780/artifact/logs-all.release.2/1617166227559_rolling_upgrade_test.RollingUpgradeTest.test_rolling_upgrade/node1.log:
```
Scylla version 4.3.0-0.20210110.000585522 with build-id 7fab6c35a5d403f3416292b37c9a9aa94fe4db1f starting ...
command used: "/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ns8k1n5/test/node1/bin/scylla --options-file /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ns8k1n5/test/node1/conf/scylla.yaml --log-to-stdout 1 --api-address 127.0.51.1 --collectd-hostname d8061d688155.node1 --smp 2 --memory 1024M --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.51.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1"
parsed command line options: [options-file: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-5ns8k1n5/test/node1/conf/scylla.yaml, log-to-stdout: 1, api-address: 127.0.51.1, collectd-hostname: d8061d688155.node1, smp: 2, memory: 1024M, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, developer-mode: true, default-log-level: info, collectd: 0, overprovisioned, prometheus-address: 127.0.51.1, unsafe-bypass-fsync: 1, kernel-page-cache, (positional) 1]
error: unrecognised option '--kernel-page-cache'
```

The option was recently introduced in scylladb/scylla@8785dd62cb740522d80eb12f8272081f85be9b7e
and is not available in any release up to and including 4.4.0.

**Comment by bhalevy** [comment]
Hit the same issue also in:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/780/artifact/logs-all.release.2/1617166248627_upgrade_test.UpgradeTestFrom40ToLast.test_cluster_upgrade/node1.log
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/780/artifact/logs-all.release.2/1617166267412_upgrade_test.UpgradeTestFrom40ToLast.test_one_node_upgrade/node1.log

**Comment by avikivity** [comment]
Ah. I suppose we have to check if the option is available (with scylla --help) before using it.

I wanted to do this, but it was too difficult for my understanding of ccm.
