### ISSUE TITLE
start-all.sh unexpected hyphen 

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-ccm#323]
I'm passing an extra argument to 'start-all.sh' to enable the Prometheus admin API using:

```
./start-all.sh -b --web.enable-admin-api
```

The problem is that the Prometheus container fails with the following message:
```
Error parsing commandline arguments: unknown long flag '---web.enable-admin-api'
prometheus: error: unknown long flag '---web.enable-admin-api'
```

As you can see, there are 3 hypens, and I only passed 2.

If I change my startup command to
```
./start-all.sh -b -web.enable-admin-api
```
It will add an extra hyphen en the containers start fine.

My Scylla manager version: 3.6.3

**Comment by bhalevy** [comment]
@pveentjer I'm not familiar with `start-all.sh`.
What repository is it part of?

**Comment by pveentjer** [comment]
Good question :) 

It is part of scylla-monitoring. It is one of the shell scripts in the main directory.

But I guess I was smoking something because I don't think this is the appropriate repo for this ticket.
