### ISSUE TITLE
stop supporting python2

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylla-ccm#432]
just realized that we even support python2! what the reason of behind this or we just haven't got a chance of updating https://github.com/scylladb/scylla-ccm/blob/e4c0589450f0df667cb2fd1e0f3c51afed2e54e5/setup.py#L32-L34 and remove all the code using `six`?

@fruch hi Israel, what do you think? i'd volunteer for this cleanup piecemeal with your blessings. as i miss the python3 features, and don't really want to use `six` or `__future__` in 2023.

**Comment by fruch** [comment]
We had a few places where CCM was used with python2, I believe all of them are gone by now.

Also we have better unit test coverage now, and a fast way to test all of dtest cases.

So it should be quite straight forward, 
If you have bandwidth for it, go for it.

**Comment by fruch** [comment]
We had a few places where CCM was used with python2, I believe all of them are gone by now.

Also we have better unit test coverage now, and a fast way to test all of dtest cases.

So it should be quite straight forward, 
If you have bandwidth for it, go for it.

**Comment by fruch** [comment]
We had a few places where CCM was used with python2, I believe all of them are gone by now.

Also we have better unit test coverage now, and a fast way to test all of dtest cases.

So it should be quite straight forward, 
If you have bandwidth for it, go for it.
