### ISSUE TITLE
Only the first occurrence  `--experimental-features` in `SCYLLA_EXT_OPTS` is used

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla-ccm#540]
ccm don't seem to support Scylla command line options that can be repeated with different values,
when trying to use it with:
`export SCYLLA_EXT_OPTS="--experimental-features consistent-topology-changes --experimental-features tablets"`

Only the first option is given to Scylla (evident in node logs and actual enabled functionality).

**Comment by Bouncheck** [comment]
I've encountered the same problem when writing tablets tests for java-driver.  It would be great if this got resolved.
