### ISSUE TITLE
ScyllaNode: override get_highest_supported_sstable_version using scylla api

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#589]
Based on https://github.com/scylladb/scylladb/issues/19772, let's override `Node.get_highest_supported_sstable_version` in the `ScyllaNode` class, and invoke the new system api to `get_highest_supported_sstable_version`.

This would allow upgrade dtest to work with the latest versiosn (that have ME_SSTABLE_FORMAT enabled by default, without a corresponding cluster feature, that the existing implementation of `get_highest_supported_sstable_version` depends on)

**Comment by bhalevy** [comment]
Note that the implementation needs to be backward compatible so it'd work also with old versions that don't support the new api yet.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/issues/19772 is fixed so the new api is available.
We can start implementing this libccm function that depends on it.

**Comment by bhalevy** [comment]
@Lakshmipathi what's the verdict for this PR, can it be closed?

Cc @pehala

**Comment by Lakshmipathi** [comment]
@bhalevy I see your latest comment here https://github.com/scylladb/scylla-dtest/pull/4809  after fixing it, it can be merged.
