### ISSUE TITLE
scylla_repository setup should support scylla-debug in the version format

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-ccm#590]
Currently the `version` format supported by scylla_repository.setup can be either:
`unstable/<branch>:<build-date>` (build-date can be `latest` as well)
or
`release:<release-number>`

And on top of it we use a couple of environment variables to specify some more attributes:
`SCYLLA_PRODUCT` can be `scylla` or `scylla-enterprise` (default is `scylla`)
`SCYLLA_ARCH` can `x86_64` or `aarch64` (default is `x86_64`)

But, there is no way to specify `scylla-debug` vs. `scylla` for the unified package.

I really don't like the use of the environment variables for the extra attributes.
Maybe we should extend the version syntax to allow passing them with the version string, as well as the `debug` flag.

**Comment by bhalevy** [comment]
Cc @fruch @cezarmoise

**Comment by fruch** [comment]
`SCYLLA_PRODUCT` is not needed anymore, it can assume it from the version use, or from the branch names.

`SCYLLA_ARCH` is expected to be automatically set, base on the system arch, I don't think it add anything, adding it to the syntax.

debug might be nice addition, as optional extra information:

`unstable/<branch>:<build-date>:debug`
`release:<release-number>:debug`

**Comment by bhalevy** [comment]
@fruch please see https://github.com/scylladb/scylla-ccm/pull/591

I think that parsing of the flags better be done as `[flags...]` instead of another column separated field.

**Comment by pehala** [comment]
@fruch @bhalevy should we reopen this, since this got yanked?

**Comment by fruch** [comment]
Yes, it would need to be applied again, and fixed
