### ISSUE TITLE
ccmlib should work when scylla-tools not installed

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-ccm#617]
The issue is bit like https://github.com/scylladb/scylla-cluster-tests/issues/8799 and related with https://github.com/scylladb/scylladb/pull/20740, we are removing scylla-tools from default installation (and we will completely drop scylla-tools later).

But when I tested a PR to drop scylla-tools from unified package, dtest failed with:
```
21:44:43  Traceback (most recent call last):
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/bin/ccm", line 74, in <module>
21:44:43      cmd.run()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cmds/cluster_cmds.py", line 269, in run
21:44:43      cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 327, in populate
21:44:43      self.new_node(i, debug=debug, initial_token=tk, data_center=dc, rack=rack)
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 334, in new_node
21:44:43      node = self.create_node(name=f'node{i}',
21:44:43             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_cluster.py", line 93, in create_node
21:44:43      return ScyllaNode(name, self, auto_bootstrap, None,
21:44:43             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 51, in __init__
21:44:43      super().__init__(name, cluster, auto_bootstrap,
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/node.py", line 126, in __init__
21:44:43      self.import_config_files()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 975, in import_config_files
21:44:43      self.copy_config_files()
21:44:43    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 981, in copy_config_files
21:44:43      conf_pattern = os.path.join(self.get_tools_java_dir(), 'conf', "jvm*.options")
21:44:43                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21:44:43    File "<frozen posixpath>", line 76, in join
21:44:43  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Seems like ccmlib/scylla_node.py is not allowed to remove scylla-tools directory, but we need to do so.

**Comment by fruch** [comment]
Code needs to be adjusted, like @tchaikov and @denesb did it for nodetool and for jmx existence.

**Comment by syuu1228** [comment]
There are more errors related with `get_tools_java_dir()`:
```
07:51:05  Traceback (most recent call last):
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/bin/ccm", line 74, in <module>
07:51:05      cmd.run()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cmds/cluster_cmds.py", line 269, in run
07:51:05      cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 330, in populate
07:51:05      self.new_node(i, debug=debug, initial_token=tk, data_center=dc, rack=rack)
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/cluster.py", line 337, in new_node
07:51:05      node = self.create_node(name=f'node{i}',
07:51:05             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_cluster.py", line 94, in create_node
07:51:05      return ScyllaNode(name, self, auto_bootstrap, None,
07:51:05             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 53, in __init__
07:51:05      super().__init__(name, cluster, auto_bootstrap,
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/node.py", line 128, in __init__
07:51:05      self.import_config_files()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 979, in import_config_files
07:51:05      self.__copy_logback_files()
07:51:05    File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.12/site-packages/ccmlib/scylla_node.py", line 1003, in __copy_logback_files
07:51:05      shutil.copy(os.path.join(self.get_tools_java_dir(), 'conf', 'logback-tools.xml'),
07:51:05
```
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11904/consoleFull

**Comment by syuu1228** [comment]
I found some more fixes to make ccmlib able to work without scylla-tools, by the patch attached below.
However, I found that we actually cannot able to run scylla-dtest without scylla-tools since it requires Java based sstable* commands witch is provided by scylla-tools:
 https://github.com/scylladb/scylladb/pull/20740#issuecomment-2392218955

Since it actually doesn't fix the problem, I'm not sure I should merge the patch or not.

- ccmlib patch
```
diff --git a/ccmlib/scylla_node.py b/ccmlib/scylla_node.py
index 4833ed4..9c40667 100644
--- a/ccmlib/scylla_node.py
+++ b/ccmlib/scylla_node.py
@@ -151,9 +151,11 @@ class ScyllaNode(Node):
     def get_tool(self, toolname):
         candidate_dirs = [
             os.path.join(self.node_install_dir, 'share', 'cassandra', BIN_DIR),
-            os.path.join(self.get_tools_java_dir(), BIN_DIR),
             os.path.join(self.get_cqlsh_dir(), BIN_DIR),
         ]
+        tools_java_dir = self.get_tools_java_dir()
+        if tools_java_dir:
+            candidate_dirs.append(os.path.join(tools_java_dir, BIN_DIR))
         for candidate_dir in candidate_dirs:
             candidate = shutil.which(toolname, path=candidate_dir)
             if candidate:
@@ -167,8 +169,12 @@ class ScyllaNode(Node):
         update_conf = not self.__conf_updated
         if update_conf:
             self.__conf_updated = True
-        return common.make_cassandra_env(self.get_install_cassandra_root(),
-                                         self.get_node_cassandra_root(), update_conf=update_conf)
+        tools_java_dir = self.get_tools_java_dir()
+        if not tools_java_dir:
+            return os.environ.copy()
+        else:
+            return common.make_cassandra_env(self.get_install_cassandra_root(),
+                                             self.get_node_cassandra_root(), update_conf=update_conf)
 
     def _get_environ(self, extra_env = None, /, **kwargs):
         try:
@@ -1000,7 +1006,12 @@ class ScyllaNode(Node):
         return os.path.join(self.node_install_dir, 'tools', 'cqlsh')
 
     def __copy_logback_files(self):
-        shutil.copy(os.path.join(self.get_tools_java_dir(), 'conf', 'logback-tools.xml'),
+        tools_java_dir = self.get_tools_java_dir()
+        if not tools_java_dir:
+            # in newer scylla, the java-base scylla-tools is dropped, so this
+            # directory cannot be found in that case.
+            return
+        shutil.copy(os.path.join(tools_java_dir, 'conf', 'logback-tools.xml'),
                     os.path.join(self.get_conf_dir(), 'logback-tools.xml'))
 
     def import_dse_config_files(self):
@@ -1045,23 +1056,25 @@ class ScyllaNode(Node):
 
 
     def import_bin_files(self, exist_ok=False, replace=False):
-        # selectively copying files to reduce risk of using unintended items
-        self._copy_binaries(files=[CASSANDRA_SH, 'nodetool'],
-                            src_path=os.path.join(self.get_tools_java_dir(), BIN_DIR),
-                            dest_path=os.path.join(self.get_path(), 'resources', 'cassandra', BIN_DIR),
-                            exist_ok=exist_ok,
-                            replace=replace
-                            )
-
-        # selectively copying files to reduce risk of using unintended items
-        # Copy sstable tools
-        self._copy_binaries(files=['sstabledump', 'sstablelevelreset', 'sstablemetadata',
-                                   'sstablerepairedset', 'sstablesplit'],
-                            src_path=os.path.join(self.get_tools_java_dir(), 'tools', BIN_DIR),
-                            dest_path=os.path.join(self.get_path(), 'resources', 'cassandra', 'tools', BIN_DIR),
-                            exist_ok=exist_ok,
-                            replace=replace
-                            )
+        tools_java_dir = self.get_tools_java_dir()
+        if tools_java_dir:
+            # selectively copying files to reduce risk of using unintended items
+            self._copy_binaries(files=[CASSANDRA_SH, 'nodetool'],
+                                src_path=os.path.join(tools_java_dir, BIN_DIR),
+                                dest_path=os.path.join(self.get_path(), 'resources', 'cassandra', BIN_DIR),
+                                exist_ok=exist_ok,
+                                replace=replace
+                                )
+
+            # selectively copying files to reduce risk of using unintended items
+            # Copy sstable tools
+            self._copy_binaries(files=['sstabledump', 'sstablelevelreset', 'sstablemetadata',
+                                       'sstablerepairedset', 'sstablesplit'],
+                                src_path=os.path.join(tools_java_dir, 'tools', BIN_DIR),
+                                dest_path=os.path.join(self.get_path(), 'resources', 'cassandra', 'tools', BIN_DIR),
+                                exist_ok=exist_ok,
+                                replace=replace
+                                )
 
         # TODO: - currently no scripts only executable - copying exec
         if self.is_scylla_reloc():
```

**Comment by denesb** [comment]
I will try to send a PR next week to eliminate remaining usage of scylla-tools in dtest.

**Comment by roydahan** [comment]
> I will try to send a PR next week to eliminate remaining usage of scylla-tools in dtest.

@denesb what are you planning to do here?

It seems like the [PR](https://github.com/scylladb/scylla-ccm/pull/619) from @tchaikov was a step in the correct direction.
Most (or even all) of the failing tests are failing for 3 main tools that are missing:
- sstableloader
- sstabledump
- cqlsh (which shouldn't be taken from scylla-tools anyway).

Now, we need to decide where to take 'sstableloader' and 'sstabledump' from.
A temporary solution until we have them as 'scylla native tools' could be to copy them from scylla-tools-java.

cqlsh, should have an easy workaround to take it from the correct place of our cqlsh.

**Comment by denesb** [comment]
> Now, we need to decide where to take 'sstableloader' and 'sstabledump' from. A temporary solution until we have them as 'scylla native tools' could be to copy them from scylla-tools-java.

`sstableloader` is deprecated and we will remove it. How exactly we will replace it is still debated. See https://github.com/scylladb/scylladb/issues/14857.
`sstabledump` already has a feature-complete replacement (`scylla sstable dump-data`). All tests using `sstabledump` should either be migrated to the native replacement, or deleted (if they are testing `sstabledump` itself).

We have one more tool which needs a native replacement: `sstablelevelreset`.

All this is tracked in https://github.com/scylladb/scylladb/issues/14856, although information there might not be completely up-to-date.

**Comment by roydahan** [comment]
Thanks @denesb 

> `sstableloader` is deprecated and we will remove it. How exactly we will replace it is still debated. See [scylladb/scylladb#14857](https://github.com/scylladb/scylladb/issues/14857). 

How is it already been deprecated if we don't have an alternative?
The current tests we have there are testing loading of cassandra sstables (most supported formats) into scylla.


> `sstabledump` already has a feature-complete replacement (`scylla sstable dump-data`). All tests using `sstabledump` should either be migrated to the native replacement, or deleted (if they are testing `sstabledump` itself).
> 
Has anyone looked into the tests for it or the tests using it when writing the new tool (and hopefully tests)?
if the replacement is fully compatible, I beleive the that migration should be straightforward and potentially 's/sstabledump/scylla sstable dump-data/g' should do the work.

> We have one more tool which needs a native replacement: `sstablelevelreset`.
> 
Yes, you're correct and it's being used in dtest.

> All this is tracked in [scylladb/scylladb#14856](https://github.com/scylladb/scylladb/issues/14856), although information there might not be completely up-to-date.

**Comment by roydahan** [comment]
So, I don't see how this task can be completed before we complete the EPIC of https://github.com/scylladb/scylladb/issues/14856.

**Comment by denesb** [comment]
Looks like there is a parallel discussion going on in https://github.com/scylladb/scylladb/pull/20740.

> > `sstableloader` is deprecated and we will remove it. How exactly we will replace it is still debated. See [scylladb/scylladb#14857](https://github.com/scylladb/scylladb/issues/14857).
> 
> How is it already been deprecated if we don't have an alternative? The current tests we have there are testing loading of cassandra sstables (most supported formats) into scylla.

See https://github.com/scylladb/scylladb/pull/20740#issuecomment-2405831267, @avikivity said we will drop it, leaving scylla-migrator and nodetool refresh as the replacements.


> > `sstabledump` already has a feature-complete replacement (`scylla sstable dump-data`). All tests using `sstabledump` should either be migrated to the native replacement, or deleted (if they are testing `sstabledump` itself).
> 
> Has anyone looked into the tests for it or the tests using it when writing the new tool (and hopefully tests)? if the replacement is fully compatible, I beleive the that migration should be straightforward and potentially 's/sstabledump/scylla sstable dump-data/g' should do the work. update: I see it's tracked here - [scylladb/scylla-dtest#3489](https://github.com/scylladb/scylla-dtest/issues/3489)

The output of scylla sstable dump-data is not compatible with that of sstabledump. So we cannot just replace the invokation in the existing tests. I have already added a mirror of the existing tests that use scylla-sstable, see https://github.com/scylladb/scylla-dtest/pull/3245.

> 
> > We have one more tool which needs a native replacement: `sstablelevelreset`.
> 
> Yes, you're correct and it's being used in dtest.

If the only place this tool is ever used is tests, than we should drop it as @avikivity suggested in https://github.com/scylladb/scylladb/pull/20740#issuecomment-2405831267.
I have never heard of anyone using this.
